### ISSUE TITLE
npm prepublish is not run successfully 

### ISSUE THREAD

**Issue by thefotios** [drone-plugins/drone-npm#5]
My NPM package is using `prepublish` to run babel in order to not have to commit compiled assets [(rationale)](http://mammal.io/articles/using-es6-today/).

Snippet from `package.json`:
```json5
  ...
  "babel": {
    "presets": [
      "es2015"
    ]
  },
  "scripts": {
    "build": "babel src --out-dir dist",
    "prepublish": "npm run build"
  },
  "dependencies": {},
  "devDependencies": {
    "babel-cli": "^6.6.5",
    "babel-preset-es2015": "^6.6.0",
    ...
  }
```

I order to achieve this, I need to run `npm install` to get dependencies installed in order to run my build script. Maybe this should be an optional setting? This way packages that don't need it don't incur the overhead of `npm install`

**Comment by thefotios** [comment]
Interestingly, when I run this locally (with no packages installed) `npm publish`, it fails with an exit code 1. This is with `npm@2`, not sure why this works successfully in this plugin.

**Comment by tboerger** [comment]
And what do you want to do now? You can run npm install within the build process?

**Comment by thefotios** [comment]
Perhaps something like:
```go
if vargs.RunInstall {
  cmds = append(cmds, "npm install"); # in an equivalent function, this is the gist
}
```

Around https://github.com/drone-plugins/drone-npm/blob/master/main.go#L125

**Comment by donny-dont** [comment]
Is there a reason why you aren't running `npm install` in your build section @thefotios? or is this something else.

**Comment by thefotios** [comment]
I am running `npm install` in the `build` section, but do I need to have a separate section that this plugin will respect? We have an internal image with it's own section (so maybe we're doing something wrong). Here is an example:

```yml
build:
  prtest:
    image: internal_image
    environment:
      - NPM_CONFIG_USERCONFIG=.npmrc
    commands:
      - ...
      - npm install
      - ...
    when:
      event: pull_request

publish:
  npm:
    ...
    when:
      event: tag
```

**Comment by bradrydzewski** [comment]
I recommend running `npm run build` during the build phase instead of part of the plugin. We cannot guarantee an npm install inside the plugin would work due to environment issues such as missing dependencies (compiling native modules, for example). For this reason I would recommend alternate approaches -- I'll provide some follow up examples when I'm back at my desk

**Comment by thefotios** [comment]
Is there a way to run the build step in the same container that would be used during publish?

For example:
```yaml
build:
  npm:
    commands:
      - npm install
    when:
      event: tag

publish:
  npm:
    when:
      event: tag
```

**Comment by donny-dont** [comment]
The npm publish container is its own docker container. That's by design. The plugin containers tend to be based on alpine so they're small. Because of this as @bradrydzewski mentions theres a chance that there won't be any build tools for something like a native npm install.

We use the npm plugin heavily at work. Typically we just have an .npmignore if there's something we don't want pushed. Have you added an .npmignore to make sure whatever files you don't want pushed aren't @thefotios?

**Comment by thefotios** [comment]
Yea, it's more about files that I *do* want published being there (and they're not checked into git). For instance, we are writing all of our module in ES6 and then compiling it manually when we merge a PR and publish a tag. This is a potentially error prone process (eg, somebody makes a quick change and forgets to recompile) and one of the reasons `prepublish` exists (see the article I posted in the initial comment).

If we were to do this manually, we would `.gitignore` our compiled directory and `.npmignore` our ES6 directory. Then our `master` branch only contains ES6 code, as do our github release artifacts. But when we `npm publish` it compiles ahead of time (and if there is an issue, it will refuse to publish). It also omits the ES6 directory (which cuts the package size in half).

**Comment by donny-dont** [comment]
I'll give you an example of something I have at work. Maybe this will clarify what I personally do with the npm plugin.

I have the following build script that is run by drone.

```
build:
  image: mycustomimage
  commands:
  - npm install
  - grunt deps
  - grunt
```

This will compile files out into a `dist` directory.

Because of that my .gitignore has

```
...

# Compilation directory
dist
```

And then in my .npmignore I do

```
# Ignore everything
*

# Output
!dist/*.js
```

I don't know why you wouldn't want to compile out each build because you'd want to catch any compilation errors.

**Comment by thefotios** [comment]
That makes sense, but for some reason, my `build` step is not being run before the `publish`. I'll try to track this down, it might be something odd with our drone setup.

**Comment by donny-dont** [comment]
It might be because of your `when` clauses.

**Comment by donny-dont** [comment]
@thefotios this get sorted for you?

**Comment by jasonkarns** [comment]
> The npm publish container is its own docker container. That's by design. The plugin containers tend to be based on alpine so they're small.

So does this mean that drone plugins can't use npm's out-of-the-box `prepublish` script? (specifically intended to be used as the pre-publish build step?)

It seems that having the `publish` plugin in a separate container (one in which `npm install` hasn't been run and therefore doesn't have the necessary build-step dependencies) breaks npm's `prepublish` capability.

**Comment by donny-dont** [comment]
@jasonkarns `prepublish` is a script. That script can do anything it wants. Because of that there are no guarantees that all that is needed for the `prepublish` can be accomplished within the image of the plugin.

As an example lets say it needed SASS and specifically the Ruby implementation. That would not be on the image and would therefor break.

I think I just need to make a note of this in the docs or something.

**Comment by jasonkarns** [comment]
> As an example lets say it needed SASS and specifically the Ruby implementation. That would not be on the image and would therefor break.

I don't think anyone in this thread was talking about dependencies outside of npm's control. I'm just trying to clarify whether the project's own devDependencies (via npm install) are available throughout npm's publish lifecycle.

**Comment by donny-dont** [comment]
The plugin runs in the same directory as the checked out repository. It has access to whatever was run in a previous pipeline step.

I cannot guarantee that anything in that previous step will be able to run within the context of the plugin. So if you did an `npm install` in the previous step and it was a native module that is compiled out it might not run if referenced in the `prepublish`.

If the plugin does not work for you then you can always run a full node container and do the publish yourself.

**Comment by jasonkarns** [comment]
@donny-dont thanks for the clarification
